export const ProductsModul = [
  {
    alt: "product-1",
    id: "product-1",
    name: "SAMSUNG Galaxy S20 FE 5G ",
    image: "images/products/1 (1).png",
    desc: "Factory Unlocked Android Cell Phone 128GB US Version Smartphone Pro-Grade",
    discount: "12%",
    price: "7.92",
  },
  {
    alt: "product-2",
    id: "product-2",
    name: "SAMSUNG Galaxy S21",
    desc: "Factory Unlocked Android Cell Phone 128GB US Version Smartphone Pro-Grade",
    discount: "10%",
    image: "images/products/1 (2).png",
    price: "2525.92",
  },
  {
    alt: "product-3",
    id: "product-3",
    name: "SAMSUNG Galaxy a1 FE 5G ",
    desc: "Factory Unlocked Android Cell Phone 128GB US Version Smartphone Pro-Grade",
    discount: "20%",
    image: "images/products/1 (3).png",
    price: "4244.92",
  },
  {
    alt: "product-4",
    id: "product-4",
    name: "SAMSUNG Galaxy S20 FE 5G",
    desc: "Factory Unlocked Android Cell Phone 128GB US Version Smartphone Pro-Grade",
    discount: "50%",
    image: "images/products/1 (4).png",
    price: "2.92",
  },
  {
    alt: "product-5",
    id: "product-5",
    name: "SAMSUNG Galaxy S20 FE 5G",
    desc: "Factory Unlocked Android Cell Phone 128GB US Version Smartphone Pro-Grade",
    discount: "30%",
    image: "images/products/1 (5).png",
    price: "123.92",
  },
  {
    alt: "product-6",
    id: "product-6",
    name: "SAMSUNG Galaxy S20 FE 5H",
    desc: "Factory Unlocked Android Cell Phone 128GB US Version Smartphone Pro-Grade",
    discount: "2%",
    image: "images/products/1 (6).png",
    price: "123.92",
  },
];
