export const CartLineModul = [
  {
    alt: "product-1",
    id: "product-1",
    image: "images/products/1 (1).png",
    desc: "NUU B15 4G LTE Unlocked Android Smartphone | 6.78” FHD+ Display with 90Hz Refresh Rate",
    value: "2",
    price: "199.99",
    subtotal: "199.9 ",
  },
  {
    alt: "product-2",
    id: "product-2",
    image: "images/products/1 (2).png",
    desc: "NUU B15 4G LTE Unlocked Android Smartphone | 6.78” FHD+ Display with 90Hz Refresh Rate",
    value: "3",
    price: "555.99",
    subtotal: "555.9 ",
  },
  {
    alt: "product-3",
    id: "product-3",
    image: "images/products/1 (3).png",
    desc: "NUU B15 4G LTE Unlocked Android Smartphone | 6.78” FHD+ Display with 90Hz Refresh Rate",
    value: "1",
    price: "222.99",
    subtotal: "222.9 ",
  },
  {
    alt: "product-4",
    id: "product-4",
    image: "images/products/1 (4).png",
    desc: "NUU B15 4G LTE Unlocked Android Smartphone | 6.78” FHD+ Display with 90Hz Refresh Rate",
    value: "4",
    price: "444.99",
    subtotal: "444.9 ",
  },
];
